### ISSUE TITLE
Upgrade solr example to docker-compose 2+

### ISSUE THREAD

**Issue by grayside** [phase2/outrigger-examples#3]
In docker-compose 2+ the preference is to used a named volume to persist data, rather than data containers. In schema v3+, volumes_from is removed.

This means replacing `volumes_from` with a normal `volume` statement:
```yaml
      - search-data:/var/lib/solr
```

Next, the docker-compose manifest will need a simple volume declaration such as:
```yaml
volumes:
  # This data volume persists Solr storage.
  # The search service is using a customized Docker image to facilitate write
  # access to this volume.
  # An empty value indicates all settings are default.
  search-data:
```

Lastly, since we are no longer using a data container, we need to instead customize our docker image to have a place to store the data. In examining the [upstream solr image](https://github.com/docker-solr/docker-solr/blob/master/5.5/alpine/Dockerfile), it appears we **could** simply locate the data within /opt/solr. Since we are not, we will need a Dockerfile such as:

```Dockerfile
FROM solr:5.5.4-alpine

USER root

# Create and permission the data directory.
RUN mkdir -pv /var/lib/solr && chown $SOLR_USER:$SOLR_USER /var/lib/solr

# Restore use of the Solr user for container operations.
USER $SOLR_USER
```

Now, we could conceivably follow the existing data container configuration to add s6 and confd to the solr container, but when I tried that I got some errors so I stepped back to this simpler approach.

Note that our current example uses solr:5.5, but in my current project implementation I decided to specify a specific patch-level, and use the alpine variant because I'm optimizing for local development access to the Solr service. I believe those could be switched back without otherwise changing what I'm demonstrating.

**Comment by scottalan** [comment]
@grayside 

Could you elaborate further as to what these changes mean for someone with solr setup with the following containers? Maybe a more verbose example as to what actually needs to change.

```
solr:
    container_name: atmosphere_${DOCKER_ENV:-local}_solr
    image: solr:5.5.4
    network_mode: "bridge"
    labels:
      com.dnsdock.name: solr
      com.dnsdock.image: atmosphere
    # For each core you want automatically available add a solr
    # configuration directory mapped under /opt/solr/server/solr
    # The configurations should set the data area for their core
    # to a directory under /var/lib/solr.
    volumes:
      # We make this a unique path so that there are no conflicts with other
      # projects running solr in the container.
      - ./env/solr/core01:/opt/solr/server/solr/atm
    volumes_from:
      - solr_data

# This container exists to allow setting the data area of solr to
  # a persistent storage area and fixing permissions so that the solr
  # container can write to it. This does not need to be done per core.
  solr_data:
    container_name: atmosphere_${DOCKER_ENV:-local}_solr_data
    network_mode: "bridge"
    build: ./env/solr_data
    volumes:
      # We make this a unique path so that there are no conflicts with other
      # projects running solr in the container.
      - /data/solr/solr:/var/lib/solr/atmosphere
```
The `Dockerfile` referenced above: `./env/solr_data` contains:

```
# Use phase2/servicebase which is already set up for fix-attrs.d

FROM phase2/servicebase

VOLUME ["/var/lib/solr"]

ADD root /
```
